export const ActionTypes = {

  REGISTER_START: "REGISTER_START",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  LOGOUT_START: "LOGOUT_START",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAIL: "LOGOUT_FAIL",

  SET_USER: "SET_USER",
  AUTHENTICATED_USER: "AUTHENTICATED_USER",


  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  CART_PRODUCT: "CART_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
  SET_SHIPPING_METHOD: 'SET_SHIPPING_METHOD',
  SET_PAYMENT_METHOD: 'SET_PAYMENT_METHOD'
};
